// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcFaceSurface.h"

namespace ifc4
{
   class IfcAdvancedFace : public IfcFaceSurface
   {
   public:
      virtual ~IfcAdvancedFace(){}

      explicit IfcAdvancedFace() = default;

      explicit IfcAdvancedFace(const std::vector<IfcFaceBound*>& _Bounds, IfcSurface* _FaceSurface, const IfcBoolean& _SameSense)
         : IfcFaceSurface(_Bounds, _FaceSurface, _SameSense) {}

      virtual std::string className() const { return "IfcAdvancedFace"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Bounds);
         w.writeAttributeInstance(FaceSurface);
         w.writeAttributeValue(SameSense);
         w.endEntity();
      }

   };

} // namespace ifc4

