// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"

#include "IfcOrganization.h"
#include "IfcPerson.h"
#include "IfcPersonAndOrganization.h"

namespace ifc4
{
   typedef boost::variant<IfcOrganization*, IfcPerson*, IfcPersonAndOrganization*> IfcActorSelect;

   class IfcActorSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcActorSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcOrganization* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPerson* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPersonAndOrganization* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
