// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"

#include "IfcCoordinateReferenceSystem.h"
#include "IfcGeometricRepresentationContext.h"

namespace ifc4
{
   typedef boost::variant<IfcCoordinateReferenceSystem*, IfcGeometricRepresentationContext*> IfcCoordinateReferenceSystemSelect;

   class IfcCoordinateReferenceSystemSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcCoordinateReferenceSystemSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcCoordinateReferenceSystem* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcGeometricRepresentationContext* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
