// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcGeometricRepresentationItem.h"

namespace ifc4
{
   class IfcDirection : public IfcGeometricRepresentationItem
   {
   public:
      virtual ~IfcDirection(){}

      explicit IfcDirection() = default;

      explicit IfcDirection(const std::vector<IfcReal>& _DirectionRatios)
         : IfcGeometricRepresentationItem(), DirectionRatios(_DirectionRatios) {}

      virtual std::string className() const { return "IfcDirection"; }

      std::vector<IfcReal> DirectionRatios; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(DirectionRatios);
         w.endEntity();
      }

   };

} // namespace ifc4

