// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSweptAreaSolid.h"
#include "IfcDirection.h"

namespace ifc4
{
   class IfcExtrudedAreaSolid : public IfcSweptAreaSolid
   {
   public:
      virtual ~IfcExtrudedAreaSolid(){}

      explicit IfcExtrudedAreaSolid() = default;

      explicit IfcExtrudedAreaSolid(IfcProfileDef* _SweptArea, IfcDirection* _ExtrudedDirection, const IfcPositiveLengthMeasure& _Depth)
         : IfcSweptAreaSolid(_SweptArea), ExtrudedDirection(_ExtrudedDirection), Depth(_Depth) {}

      virtual std::string className() const { return "IfcExtrudedAreaSolid"; }

      IfcDirection* ExtrudedDirection; // required parameter
      boost::optional<IfcPositiveLengthMeasure> Depth; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(SweptArea);
         w.writeAttributeInstance(Position);
         w.writeAttributeInstance(ExtrudedDirection);
         w.writeAttributeValue(Depth);
         w.endEntity();
      }

   };

} // namespace ifc4

