// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcFlowStorageDeviceType.h"

namespace ifc4
{
   class IfcElectricFlowStorageDeviceType : public IfcFlowStorageDeviceType
   {
   public:
      virtual ~IfcElectricFlowStorageDeviceType(){}

      explicit IfcElectricFlowStorageDeviceType() = default;

      explicit IfcElectricFlowStorageDeviceType(const IfcGloballyUniqueId& _GlobalId, const IfcElectricFlowStorageDeviceTypeEnum& _PredefinedType)
         : IfcFlowStorageDeviceType(_GlobalId), PredefinedType(_PredefinedType) {}

      virtual std::string className() const { return "IfcElectricFlowStorageDeviceType"; }

      boost::optional<IfcElectricFlowStorageDeviceTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.writeAttributeInstance(RepresentationMaps);
         w.writeAttributeValue(Tag);
         w.writeAttributeValue(ElementType);
         w.writeAttributeValue(IfcElectricFlowStorageDeviceTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

