// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcDistributionFlowElementType.h"

namespace ifc4
{
   class IfcEnergyConversionDeviceType : public IfcDistributionFlowElementType
   {
   public:
      virtual ~IfcEnergyConversionDeviceType(){}

      explicit IfcEnergyConversionDeviceType() = default;

      explicit IfcEnergyConversionDeviceType(const IfcGloballyUniqueId& _GlobalId)
         : IfcDistributionFlowElementType(_GlobalId) {}

      virtual std::string className() const { return "IfcEnergyConversionDeviceType"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.writeAttributeInstance(RepresentationMaps);
         w.writeAttributeValue(Tag);
         w.writeAttributeValue(ElementType);
         w.endEntity();
      }

   };

} // namespace ifc4

