// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"

#include "IfcExternallyDefinedHatchStyle.h"
#include "IfcFillAreaStyleHatching.h"
#include "IfcFillAreaStyleTiles.h"

namespace ifc4
{
   typedef boost::variant<IfcColour, IfcExternallyDefinedHatchStyle*, IfcFillAreaStyleHatching*, IfcFillAreaStyleTiles*> IfcFillStyleSelect;

   class IfcFillStyleSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcFillStyleSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcColour p) const
      {
         m_w.writeAttributeValue(p);
      }
      void operator() (IfcExternallyDefinedHatchStyle* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcFillAreaStyleHatching* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcFillAreaStyleTiles* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
