// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcTextureCoordinate.h"
#include "IfcTessellatedFaceSet.h"
#include "IfcTextureVertexList.h"

namespace ifc4
{
   class IfcIndexedTextureMap : public IfcTextureCoordinate
   {
   public:
      virtual ~IfcIndexedTextureMap(){}

      explicit IfcIndexedTextureMap() = default;

      explicit IfcIndexedTextureMap(const std::vector<IfcSurfaceTexture*>& _Maps, IfcTessellatedFaceSet* _MappedTo, IfcTextureVertexList* _TexCoords)
         : IfcTextureCoordinate(_Maps), MappedTo(_MappedTo), TexCoords(_TexCoords) {}

      virtual std::string className() const { return "IfcIndexedTextureMap"; }

      IfcTessellatedFaceSet* MappedTo; // required parameter
      IfcTextureVertexList* TexCoords; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Maps);
         w.writeAttributeInstance(MappedTo);
         w.writeAttributeInstance(TexCoords);
         w.endEntity();
      }

   };

} // namespace ifc4

