// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcLightSource.h"
#include "IfcDirection.h"

namespace ifc4
{
   class IfcLightSourceDirectional : public IfcLightSource
   {
   public:
      virtual ~IfcLightSourceDirectional(){}

      explicit IfcLightSourceDirectional() = default;

      explicit IfcLightSourceDirectional(IfcColourRgb* _LightColour, IfcDirection* _Orientation)
         : IfcLightSource(_LightColour), Orientation(_Orientation) {}

      virtual std::string className() const { return "IfcLightSourceDirectional"; }

      IfcDirection* Orientation; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeInstance(LightColour);
         w.writeAttributeValue(AmbientIntensity);
         w.writeAttributeValue(Intensity);
         w.writeAttributeInstance(Orientation);
         w.endEntity();
      }

   };

} // namespace ifc4

