// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcConstructionResourceType.h"

namespace ifc4
{
   class IfcLaborResourceType : public IfcConstructionResourceType
   {
   public:
      virtual ~IfcLaborResourceType(){}

      explicit IfcLaborResourceType() = default;

      explicit IfcLaborResourceType(const IfcGloballyUniqueId& _GlobalId, const IfcLaborResourceTypeEnum& _PredefinedType)
         : IfcConstructionResourceType(_GlobalId), PredefinedType(_PredefinedType) {}

      virtual std::string className() const { return "IfcLaborResourceType"; }

      boost::optional<IfcLaborResourceTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.writeAttributeValue(Identification);
         w.writeAttributeValue(LongDescription);
         w.writeAttributeValue(ResourceType);
         w.writeAttributeInstance(BaseCosts);
         w.writeAttributeInstance(BaseQuantity);
         w.writeAttributeValue(IfcLaborResourceTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

