// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcActor.h"

namespace ifc4
{
   class IfcOccupant : public IfcActor
   {
   public:
      virtual ~IfcOccupant(){}

      explicit IfcOccupant() = default;

      explicit IfcOccupant(const IfcGloballyUniqueId& _GlobalId, const IfcActorSelect& _TheActor)
         : IfcActor(_GlobalId, _TheActor) {}

      virtual std::string className() const { return "IfcOccupant"; }

      boost::optional<IfcOccupantTypeEnum> PredefinedType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeSelect<IfcActorSelectWriterVisitor>(TheActor);
         w.writeAttributeValue(IfcOccupantTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

