// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcExtendedProperties.h"
#include "IfcProfileDef.h"

namespace ifc4
{
   class IfcProfileProperties : public IfcExtendedProperties
   {
   public:
      virtual ~IfcProfileProperties(){}

      explicit IfcProfileProperties() = default;

      explicit IfcProfileProperties(const std::vector<IfcProperty*>& _Properties, IfcProfileDef* _ProfileDefinition)
         : IfcExtendedProperties(_Properties), ProfileDefinition(_ProfileDefinition) {}

      virtual std::string className() const { return "IfcProfileProperties"; }

      IfcProfileDef* ProfileDefinition; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeInstance(Properties);
         w.writeAttributeInstance(ProfileDefinition);
         w.endEntity();
      }

   };

} // namespace ifc4

