// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcControl.h"

namespace ifc4
{
   class IfcPerformanceHistory : public IfcControl
   {
   public:
      virtual ~IfcPerformanceHistory(){}

      explicit IfcPerformanceHistory() = default;

      explicit IfcPerformanceHistory(const IfcGloballyUniqueId& _GlobalId, const IfcLabel& _LifeCyclePhase)
         : IfcControl(_GlobalId), LifeCyclePhase(_LifeCyclePhase) {}

      virtual std::string className() const { return "IfcPerformanceHistory"; }

      boost::optional<IfcLabel> LifeCyclePhase; // required parameter
      boost::optional<IfcPerformanceHistoryTypeEnum> PredefinedType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeValue(Identification);
         w.writeAttributeValue(LifeCyclePhase);
         w.writeAttributeValue(IfcPerformanceHistoryTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

