// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcPropertyDefinition.h"

namespace ifc4
{
   class IfcPropertyTemplateDefinition : public IfcPropertyDefinition
   {
   public:
      virtual ~IfcPropertyTemplateDefinition(){}

      explicit IfcPropertyTemplateDefinition() = default;

      explicit IfcPropertyTemplateDefinition(const IfcGloballyUniqueId& _GlobalId)
         : IfcPropertyDefinition(_GlobalId) {}

      virtual std::string className() const { return "IfcPropertyTemplateDefinition"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.endEntity();
      }

   };

} // namespace ifc4

