// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcRelAssociates.h"
#include "IfcConstraint.h"

namespace ifc4
{
   class IfcRelAssociatesConstraint : public IfcRelAssociates
   {
   public:
      virtual ~IfcRelAssociatesConstraint(){}

      explicit IfcRelAssociatesConstraint() = default;

      explicit IfcRelAssociatesConstraint(const IfcGloballyUniqueId& _GlobalId, const std::vector< boost::optional<IfcDefinitionSelect> >& _RelatedObjects, IfcConstraint* _RelatingConstraint)
         : IfcRelAssociates(_GlobalId, _RelatedObjects), RelatingConstraint(_RelatingConstraint) {}

      virtual std::string className() const { return "IfcRelAssociatesConstraint"; }

      boost::optional<IfcLabel> Intent; // optional parameter
      IfcConstraint* RelatingConstraint; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeSelect<IfcDefinitionSelectWriterVisitor>(RelatedObjects);
         w.writeAttributeValue(Intent);
         w.writeAttributeInstance(RelatingConstraint);
         w.endEntity();
      }

   };

} // namespace ifc4

