// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcReinforcingElement.h"

namespace ifc4
{
   class IfcReinforcingMesh : public IfcReinforcingElement
   {
   public:
      virtual ~IfcReinforcingMesh(){}

      explicit IfcReinforcingMesh() = default;

      explicit IfcReinforcingMesh(const IfcGloballyUniqueId& _GlobalId)
         : IfcReinforcingElement(_GlobalId) {}

      virtual std::string className() const { return "IfcReinforcingMesh"; }

      boost::optional<IfcPositiveLengthMeasure> MeshLength; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> MeshWidth; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> LongitudinalBarNominalDiameter; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> TransverseBarNominalDiameter; // optional parameter
      boost::optional<IfcAreaMeasure> LongitudinalBarCrossSectionArea; // optional parameter
      boost::optional<IfcAreaMeasure> TransverseBarCrossSectionArea; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> LongitudinalBarSpacing; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> TransverseBarSpacing; // optional parameter
      boost::optional<IfcReinforcingMeshTypeEnum> PredefinedType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValue(Tag);
         w.writeAttributeValue(SteelGrade);
         w.writeAttributeValue(MeshLength);
         w.writeAttributeValue(MeshWidth);
         w.writeAttributeValue(LongitudinalBarNominalDiameter);
         w.writeAttributeValue(TransverseBarNominalDiameter);
         w.writeAttributeValue(LongitudinalBarCrossSectionArea);
         w.writeAttributeValue(TransverseBarCrossSectionArea);
         w.writeAttributeValue(LongitudinalBarSpacing);
         w.writeAttributeValue(TransverseBarSpacing);
         w.writeAttributeValue(IfcReinforcingMeshTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

