// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"

#include "IfcActorRole.h"
#include "IfcAppliedValue.h"
#include "IfcApproval.h"
#include "IfcConstraint.h"
#include "IfcContextDependentUnit.h"
#include "IfcConversionBasedUnit.h"
#include "IfcExternalInformation.h"
#include "IfcExternalReference.h"
#include "IfcMaterialDefinition.h"
#include "IfcOrganization.h"
#include "IfcPerson.h"
#include "IfcPersonAndOrganization.h"
#include "IfcPhysicalQuantity.h"
#include "IfcProfileDef.h"
#include "IfcPropertyAbstraction.h"
#include "IfcTimeSeries.h"

namespace ifc4
{
   typedef boost::variant<IfcActorRole*, IfcAppliedValue*, IfcApproval*, IfcConstraint*, IfcContextDependentUnit*, IfcConversionBasedUnit*, IfcExternalInformation*, IfcExternalReference*, IfcMaterialDefinition*, IfcOrganization*, IfcPerson*, IfcPersonAndOrganization*, IfcPhysicalQuantity*, IfcProfileDef*, IfcPropertyAbstraction*, IfcTimeSeries*> IfcResourceObjectSelect;

   class IfcResourceObjectSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcResourceObjectSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcActorRole* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcAppliedValue* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcApproval* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcConstraint* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcContextDependentUnit* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcConversionBasedUnit* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcExternalInformation* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcExternalReference* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcMaterialDefinition* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcOrganization* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPerson* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPersonAndOrganization* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPhysicalQuantity* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcProfileDef* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcPropertyAbstraction* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcTimeSeries* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
