// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcPreDefinedPropertySet.h"
#include "IfcSectionReinforcementProperties.h"

namespace ifc4
{
   class IfcReinforcementDefinitionProperties : public IfcPreDefinedPropertySet
   {
   public:
      virtual ~IfcReinforcementDefinitionProperties(){}

      explicit IfcReinforcementDefinitionProperties() = default;

      explicit IfcReinforcementDefinitionProperties(const IfcGloballyUniqueId& _GlobalId, const std::vector<IfcSectionReinforcementProperties*>& _ReinforcementSectionDefinitions)
         : IfcPreDefinedPropertySet(_GlobalId), ReinforcementSectionDefinitions(_ReinforcementSectionDefinitions) {}

      virtual std::string className() const { return "IfcReinforcementDefinitionProperties"; }

      boost::optional<IfcLabel> DefinitionType; // optional parameter
      std::vector<IfcSectionReinforcementProperties*> ReinforcementSectionDefinitions; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(DefinitionType);
         w.writeAttributeInstance(ReinforcementSectionDefinitions);
         w.endEntity();
      }

   };

} // namespace ifc4

