// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcObject.h"

namespace ifc4
{
   class IfcResource : public IfcObject
   {
   public:
      virtual ~IfcResource(){}

      explicit IfcResource() = default;

      explicit IfcResource(const IfcGloballyUniqueId& _GlobalId)
         : IfcObject(_GlobalId) {}

      virtual std::string className() const { return "IfcResource"; }

      boost::optional<IfcIdentifier> Identification; // optional parameter
      boost::optional<IfcText> LongDescription; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeValue(Identification);
         w.writeAttributeValue(LongDescription);
         w.endEntity();
      }

   };

} // namespace ifc4

