// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcRelAssignsToGroup.h"

namespace ifc4
{
   class IfcRelAssignsToGroupByFactor : public IfcRelAssignsToGroup
   {
   public:
      virtual ~IfcRelAssignsToGroupByFactor(){}

      explicit IfcRelAssignsToGroupByFactor() = default;

      explicit IfcRelAssignsToGroupByFactor(const IfcGloballyUniqueId& _GlobalId, const std::vector<IfcObjectDefinition*>& _RelatedObjects, IfcGroup* _RelatingGroup, const IfcRatioMeasure& _Factor)
         : IfcRelAssignsToGroup(_GlobalId, _RelatedObjects, _RelatingGroup), Factor(_Factor) {}

      virtual std::string className() const { return "IfcRelAssignsToGroupByFactor"; }

      boost::optional<IfcRatioMeasure> Factor; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeInstance(RelatedObjects);
         w.writeAttributeValue(IfcObjectTypeEnumStringMap, RelatedObjectsType);
         w.writeAttributeInstance(RelatingGroup);
         w.writeAttributeValue(Factor);
         w.endEntity();
      }

   };

} // namespace ifc4

