// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcResourceLevelRelationship.h"
#include "IfcResourceObjectSelect.h"
#include "IfcApproval.h"

namespace ifc4
{
   class IfcResourceApprovalRelationship : public IfcResourceLevelRelationship
   {
   public:
      virtual ~IfcResourceApprovalRelationship(){}

      explicit IfcResourceApprovalRelationship() = default;

      explicit IfcResourceApprovalRelationship(const std::vector< boost::optional<IfcResourceObjectSelect> >& _RelatedResourceObjects, IfcApproval* _RelatingApproval)
         : IfcResourceLevelRelationship(), RelatedResourceObjects(_RelatedResourceObjects), RelatingApproval(_RelatingApproval) {}

      virtual std::string className() const { return "IfcResourceApprovalRelationship"; }

      std::vector< boost::optional<IfcResourceObjectSelect> > RelatedResourceObjects; // required parameter
      IfcApproval* RelatingApproval; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeSelect<IfcResourceObjectSelectWriterVisitor>(RelatedResourceObjects);
         w.writeAttributeInstance(RelatingApproval);
         w.endEntity();
      }

   };

} // namespace ifc4

