// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcEdge.h"
#include "IfcEdge.h"

namespace ifc4
{
   class IfcSubedge : public IfcEdge
   {
   public:
      virtual ~IfcSubedge(){}

      explicit IfcSubedge() = default;

      explicit IfcSubedge(IfcVertex* _EdgeStart, IfcVertex* _EdgeEnd, IfcEdge* _ParentEdge)
         : IfcEdge(_EdgeStart, _EdgeEnd), ParentEdge(_ParentEdge) {}

      virtual std::string className() const { return "IfcSubedge"; }

      IfcEdge* ParentEdge; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(EdgeStart);
         w.writeAttributeInstance(EdgeEnd);
         w.writeAttributeInstance(ParentEdge);
         w.endEntity();
      }

   };

} // namespace ifc4

