// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSpatialStructureElementType.h"

namespace ifc4
{
   class IfcSpaceType : public IfcSpatialStructureElementType
   {
   public:
      virtual ~IfcSpaceType(){}

      explicit IfcSpaceType() = default;

      explicit IfcSpaceType(const IfcGloballyUniqueId& _GlobalId, const IfcSpaceTypeEnum& _PredefinedType)
         : IfcSpatialStructureElementType(_GlobalId), PredefinedType(_PredefinedType) {}

      virtual std::string className() const { return "IfcSpaceType"; }

      boost::optional<IfcSpaceTypeEnum> PredefinedType; // required parameter
      boost::optional<IfcLabel> LongName; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.writeAttributeInstance(RepresentationMaps);
         w.writeAttributeValue(Tag);
         w.writeAttributeValue(ElementType);
         w.writeAttributeValue(IfcSpaceTypeEnumStringMap, PredefinedType);
         w.writeAttributeValue(LongName);
         w.endEntity();
      }

   };

} // namespace ifc4

