// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSweptSurface.h"
#include "IfcDirection.h"

namespace ifc4
{
   class IfcSurfaceOfLinearExtrusion : public IfcSweptSurface
   {
   public:
      virtual ~IfcSurfaceOfLinearExtrusion(){}

      explicit IfcSurfaceOfLinearExtrusion() = default;

      explicit IfcSurfaceOfLinearExtrusion(IfcProfileDef* _SweptCurve, IfcDirection* _ExtrudedDirection, const IfcLengthMeasure& _Depth)
         : IfcSweptSurface(_SweptCurve), ExtrudedDirection(_ExtrudedDirection), Depth(_Depth) {}

      virtual std::string className() const { return "IfcSurfaceOfLinearExtrusion"; }

      IfcDirection* ExtrudedDirection; // required parameter
      boost::optional<IfcLengthMeasure> Depth; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(SweptCurve);
         w.writeAttributeInstance(Position);
         w.writeAttributeInstance(ExtrudedDirection);
         w.writeAttributeValue(Depth);
         w.endEntity();
      }

   };

} // namespace ifc4

