// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"

#include "IfcExternallyDefinedSurfaceStyle.h"
#include "IfcSurfaceStyleLighting.h"
#include "IfcSurfaceStyleRefraction.h"
#include "IfcSurfaceStyleShading.h"
#include "IfcSurfaceStyleWithTextures.h"

namespace ifc4
{
   typedef boost::variant<IfcExternallyDefinedSurfaceStyle*, IfcSurfaceStyleLighting*, IfcSurfaceStyleRefraction*, IfcSurfaceStyleShading*, IfcSurfaceStyleWithTextures*> IfcSurfaceStyleElementSelect;

   class IfcSurfaceStyleElementSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcSurfaceStyleElementSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcExternallyDefinedSurfaceStyle* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcSurfaceStyleLighting* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcSurfaceStyleRefraction* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcSurfaceStyleShading* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcSurfaceStyleWithTextures* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
