// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcStructuralAction.h"

namespace ifc4
{
   class IfcStructuralSurfaceAction : public IfcStructuralAction
   {
   public:
      virtual ~IfcStructuralSurfaceAction(){}

      explicit IfcStructuralSurfaceAction() = default;

      explicit IfcStructuralSurfaceAction(const IfcGloballyUniqueId& _GlobalId, IfcStructuralLoad* _AppliedLoad, const IfcGlobalOrLocalEnum& _GlobalOrLocal, const IfcStructuralSurfaceActivityTypeEnum& _PredefinedType)
         : IfcStructuralAction(_GlobalId, _AppliedLoad, _GlobalOrLocal), PredefinedType(_PredefinedType) {}

      virtual std::string className() const { return "IfcStructuralSurfaceAction"; }

      boost::optional<IfcProjectedOrTrueLengthEnum> ProjectedOrTrue; // optional parameter
      boost::optional<IfcStructuralSurfaceActivityTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeInstance(AppliedLoad);
         w.writeAttributeValue(IfcGlobalOrLocalEnumStringMap, GlobalOrLocal);
         w.writeAttributeValue(DestabilizingLoad);
         w.writeAttributeValue(IfcProjectedOrTrueLengthEnumStringMap, ProjectedOrTrue);
         w.writeAttributeValue(IfcStructuralSurfaceActivityTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

