// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcStructuralConnection.h"
#include "IfcAxis2Placement3D.h"

namespace ifc4
{
   class IfcStructuralPointConnection : public IfcStructuralConnection
   {
   public:
      virtual ~IfcStructuralPointConnection(){}

      explicit IfcStructuralPointConnection() = default;

      explicit IfcStructuralPointConnection(const IfcGloballyUniqueId& _GlobalId)
         : IfcStructuralConnection(_GlobalId) {}

      virtual std::string className() const { return "IfcStructuralPointConnection"; }

      IfcAxis2Placement3D* ConditionCoordinateSystem; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeInstance(AppliedCondition);
         w.writeAttributeInstance(ConditionCoordinateSystem);
         w.endEntity();
      }

   };

} // namespace ifc4

