// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcProcess.h"
#include "IfcTaskTime.h"

namespace ifc4
{
   class IfcTask : public IfcProcess
   {
   public:
      virtual ~IfcTask(){}

      explicit IfcTask() = default;

      explicit IfcTask(const IfcGloballyUniqueId& _GlobalId, const IfcBoolean& _IsMilestone)
         : IfcProcess(_GlobalId), IsMilestone(_IsMilestone) {}

      virtual std::string className() const { return "IfcTask"; }

      boost::optional<IfcLabel> Status; // optional parameter
      boost::optional<IfcLabel> WorkMethod; // optional parameter
      boost::optional<IfcBoolean> IsMilestone; // required parameter
      boost::optional<IfcInteger> Priority; // optional parameter
      IfcTaskTime* TaskTime; // optional parameter
      boost::optional<IfcTaskTypeEnum> PredefinedType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeValue(Identification);
         w.writeAttributeValue(LongDescription);
         w.writeAttributeValue(Status);
         w.writeAttributeValue(WorkMethod);
         w.writeAttributeValue(IsMilestone);
         w.writeAttributeValue(Priority);
         w.writeAttributeInstance(TaskTime);
         w.writeAttributeValue(IfcTaskTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

