// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcTypeObject.h"

namespace ifc4
{
   class IfcTypeResource : public IfcTypeObject
   {
   public:
      virtual ~IfcTypeResource(){}

      explicit IfcTypeResource() = default;

      explicit IfcTypeResource(const IfcGloballyUniqueId& _GlobalId)
         : IfcTypeObject(_GlobalId) {}

      virtual std::string className() const { return "IfcTypeResource"; }

      boost::optional<IfcIdentifier> Identification; // optional parameter
      boost::optional<IfcText> LongDescription; // optional parameter
      boost::optional<IfcLabel> ResourceType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.writeAttributeValue(Identification);
         w.writeAttributeValue(LongDescription);
         w.writeAttributeValue(ResourceType);
         w.endEntity();
      }

   };

} // namespace ifc4

