// Automatically generated by ifclite express parser from ifc4 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcFlowController.h"

namespace ifc4
{
   class IfcValve : public IfcFlowController
   {
   public:
      virtual ~IfcValve(){}

      explicit IfcValve() = default;

      explicit IfcValve(const IfcGloballyUniqueId& _GlobalId)
         : IfcFlowController(_GlobalId) {}

      virtual std::string className() const { return "IfcValve"; }

      boost::optional<IfcValveTypeEnum> PredefinedType; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValue(Tag);
         w.writeAttributeValue(IfcValveTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc4

