// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcIShapeProfileDef.h"

namespace ifc2x3
{
   class IfcAsymmetricIShapeProfileDef : public IfcIShapeProfileDef
   {
   public:
      virtual ~IfcAsymmetricIShapeProfileDef(){}

      explicit IfcAsymmetricIShapeProfileDef() = default;

      explicit IfcAsymmetricIShapeProfileDef(const IfcProfileTypeEnum& _ProfileType, IfcAxis2Placement2D* _Position, const IfcPositiveLengthMeasure& _OverallWidth, const IfcPositiveLengthMeasure& _OverallDepth, const IfcPositiveLengthMeasure& _WebThickness, const IfcPositiveLengthMeasure& _FlangeThickness, const IfcPositiveLengthMeasure& _TopFlangeWidth)
         : IfcIShapeProfileDef(_ProfileType, _Position, _OverallWidth, _OverallDepth, _WebThickness, _FlangeThickness), TopFlangeWidth(_TopFlangeWidth) {}

      virtual std::string className() const { return "IfcAsymmetricIShapeProfileDef"; }

      boost::optional<IfcPositiveLengthMeasure> TopFlangeWidth; // required parameter
      boost::optional<IfcPositiveLengthMeasure> TopFlangeThickness; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> TopFlangeFilletRadius; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> CentreOfGravityInY; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(IfcProfileTypeEnumStringMap, ProfileType);
         w.writeAttributeValue(ProfileName);
         w.writeAttributeInstance(Position);
         w.writeAttributeValue(OverallWidth);
         w.writeAttributeValue(OverallDepth);
         w.writeAttributeValue(WebThickness);
         w.writeAttributeValue(FlangeThickness);
         w.writeAttributeValue(FilletRadius);
         w.writeAttributeValue(TopFlangeWidth);
         w.writeAttributeValue(TopFlangeThickness);
         w.writeAttributeValue(TopFlangeFilletRadius);
         w.writeAttributeValue(CentreOfGravityInY);
         w.endEntity();
      }

   };

} // namespace ifc2x3

