// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcProperty.h"
#include "IfcApproval.h"

namespace ifc2x3
{
   class IfcApprovalPropertyRelationship : public ifc::Entity
   {
   public:
      virtual ~IfcApprovalPropertyRelationship(){}

      explicit IfcApprovalPropertyRelationship() = default;

      explicit IfcApprovalPropertyRelationship(const std::vector<IfcProperty*>& _ApprovedProperties, IfcApproval* _Approval)
         : ifc::Entity(), ApprovedProperties(_ApprovedProperties), Approval(_Approval) {}

      virtual std::string className() const { return "IfcApprovalPropertyRelationship"; }

      std::vector<IfcProperty*> ApprovedProperties; // required parameter
      IfcApproval* Approval; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(ApprovedProperties);
         w.writeAttributeInstance(Approval);
         w.endEntity();
      }

   };

} // namespace ifc2x3

