// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcBooleanResult.h"

namespace ifc2x3
{
   class IfcBooleanClippingResult : public IfcBooleanResult
   {
   public:
      virtual ~IfcBooleanClippingResult(){}

      explicit IfcBooleanClippingResult() = default;

      explicit IfcBooleanClippingResult(const IfcBooleanOperator& _Operator, const IfcBooleanOperand& _FirstOperand, const IfcBooleanOperand& _SecondOperand)
         : IfcBooleanResult(_Operator, _FirstOperand, _SecondOperand) {}

      virtual std::string className() const { return "IfcBooleanClippingResult"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(IfcBooleanOperatorStringMap, Operator);
         w.writeAttributeSelect<IfcBooleanOperandWriterVisitor>(FirstOperand);
         w.writeAttributeSelect<IfcBooleanOperandWriterVisitor>(SecondOperand);
         w.endEntity();
      }

   };

} // namespace ifc2x3

