#ifndef IFC2X3_IFCBOUNDEDCURVE_H_INCLUDED
#define IFC2X3_IFCBOUNDEDCURVE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcCurve.h"

namespace ifc2x3
{
   class IfcBoundedCurve : public IfcCurve
   {
   public:
      virtual ~IfcBoundedCurve(){}

      IfcBoundedCurve() = default;

      virtual std::string name() const { return "IfcBoundedCurve"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
