// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"

namespace ifc2x3
{
   class IfcClassificationNotationFacet : public ifc::Entity
   {
   public:
      virtual ~IfcClassificationNotationFacet(){}

      explicit IfcClassificationNotationFacet() = default;

      explicit IfcClassificationNotationFacet(const IfcLabel& _NotationValue)
         : ifc::Entity(), NotationValue(_NotationValue) {}

      virtual std::string className() const { return "IfcClassificationNotationFacet"; }

      boost::optional<IfcLabel> NotationValue; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(NotationValue);
         w.endEntity();
      }

   };

} // namespace ifc2x3

