// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcCircleProfileDef.h"

namespace ifc2x3
{
   class IfcCircleHollowProfileDef : public IfcCircleProfileDef
   {
   public:
      virtual ~IfcCircleHollowProfileDef(){}

      explicit IfcCircleHollowProfileDef() = default;

      explicit IfcCircleHollowProfileDef(const IfcProfileTypeEnum& _ProfileType, IfcAxis2Placement2D* _Position, const IfcPositiveLengthMeasure& _Radius, const IfcPositiveLengthMeasure& _WallThickness)
         : IfcCircleProfileDef(_ProfileType, _Position, _Radius), WallThickness(_WallThickness) {}

      virtual std::string className() const { return "IfcCircleHollowProfileDef"; }

      boost::optional<IfcPositiveLengthMeasure> WallThickness; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(IfcProfileTypeEnumStringMap, ProfileType);
         w.writeAttributeValue(ProfileName);
         w.writeAttributeInstance(Position);
         w.writeAttributeValue(Radius);
         w.writeAttributeValue(WallThickness);
         w.endEntity();
      }

   };

} // namespace ifc2x3

