#ifndef IFC2X3_IFCCONNECTEDFACESET_H_INCLUDED
#define IFC2X3_IFCCONNECTEDFACESET_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcTopologicalRepresentationItem.h"
#include "IfcFace.h"

namespace ifc2x3
{
   class IfcConnectedFaceSet : public IfcTopologicalRepresentationItem
   {
   public:
      virtual ~IfcConnectedFaceSet(){}

      IfcConnectedFaceSet() = default;

      IfcConnectedFaceSet(const std::vector<IfcFace*>& _CfsFaces)
         : IfcTopologicalRepresentationItem(), CfsFaces(_CfsFaces) {}

      virtual std::string name() const { return "IfcConnectedFaceSet"; }

      std::vector<IfcFace*> CfsFaces; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstanceList(CfsFaces);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
