// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"

namespace ifc2x3
{
   class IfcCoordinatedUniversalTimeOffset : public ifc::Entity
   {
   public:
      virtual ~IfcCoordinatedUniversalTimeOffset(){}

      explicit IfcCoordinatedUniversalTimeOffset() = default;

      explicit IfcCoordinatedUniversalTimeOffset(const IfcHourInDay& _HourOffset, const IfcAheadOrBehind& _Sense)
         : ifc::Entity(), HourOffset(_HourOffset), Sense(_Sense) {}

      virtual std::string className() const { return "IfcCoordinatedUniversalTimeOffset"; }

      boost::optional<IfcHourInDay> HourOffset; // required parameter
      boost::optional<IfcMinuteInHour> MinuteOffset; // optional parameter
      boost::optional<IfcAheadOrBehind> Sense; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(HourOffset);
         w.writeAttributeValue(MinuteOffset);
         w.writeAttributeValue(IfcAheadOrBehindStringMap, Sense);
         w.endEntity();
      }

   };

} // namespace ifc2x3

