// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcCalendarDate.h"

namespace ifc2x3
{
   class IfcClassification : public ifc::Entity
   {
   public:
      virtual ~IfcClassification(){}

      explicit IfcClassification() = default;

      explicit IfcClassification(const IfcLabel& _Source, const IfcLabel& _Edition, const IfcLabel& _Name)
         : ifc::Entity(), Source(_Source), Edition(_Edition), Name(_Name) {}

      virtual std::string className() const { return "IfcClassification"; }

      boost::optional<IfcLabel> Source; // required parameter
      boost::optional<IfcLabel> Edition; // required parameter
      IfcCalendarDate* EditionDate; // optional parameter
      boost::optional<IfcLabel> Name; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Source);
         w.writeAttributeValue(Edition);
         w.writeAttributeInstance(EditionDate);
         w.writeAttributeValue(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

