#ifndef IFC2X3_IFCCONNECTIONPOINTGEOMETRY_H_INCLUDED
#define IFC2X3_IFCCONNECTIONPOINTGEOMETRY_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcConnectionGeometry.h"
#include "IfcPointOrVertexPoint.h"
#include "IfcPointOrVertexPoint.h"

namespace ifc2x3
{
   class IfcConnectionPointGeometry : public IfcConnectionGeometry
   {
   public:
      virtual ~IfcConnectionPointGeometry(){}

      IfcConnectionPointGeometry() = default;

      IfcConnectionPointGeometry(const IfcPointOrVertexPoint& _PointOnRelatingElement)
         : IfcConnectionGeometry(), PointOnRelatingElement(_PointOnRelatingElement) {}

      virtual std::string name() const { return "IfcConnectionPointGeometry"; }

      boost::optional<IfcPointOrVertexPoint> PointOnRelatingElement; // required parameter
      boost::optional<IfcPointOrVertexPoint> PointOnRelatedElement; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeSelect<IfcPointOrVertexPointWriterVisitor>(PointOnRelatingElement);
         w.writeAttributeSelect<IfcPointOrVertexPointWriterVisitor>(PointOnRelatedElement);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
