#ifndef IFC2X3_IFCDATETIMESELECT_H_INCLUDED
#define IFC2X3_IFCDATETIMESELECT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"

#include "IfcCalendarDate.h"
#include "IfcLocalTime.h"
#include "IfcDateAndTime.h"

namespace ifc2x3
{
   typedef boost::variant<IfcCalendarDate*, IfcLocalTime*, IfcDateAndTime*> IfcDateTimeSelect;

   class IfcDateTimeSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcDateTimeSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcCalendarDate* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcLocalTime* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcDateAndTime* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
#endif
