#ifndef IFC2X3_IFCDISTRIBUTIONPORT_H_INCLUDED
#define IFC2X3_IFCDISTRIBUTIONPORT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcPort.h"

namespace ifc2x3
{
   class IfcDistributionPort : public IfcPort
   {
   public:
      virtual ~IfcDistributionPort(){}

      IfcDistributionPort() = default;

      IfcDistributionPort(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcPort(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcDistributionPort"; }

      boost::optional<IfcFlowDirectionEnum> FlowDirection; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValueEnumeration(IfcFlowDirectionEnumStringMap, FlowDirection);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
