// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcDimensionCurveDirectedCallout.h"

namespace ifc2x3
{
   class IfcDiameterDimension : public IfcDimensionCurveDirectedCallout
   {
   public:
      virtual ~IfcDiameterDimension(){}

      explicit IfcDiameterDimension() = default;

      explicit IfcDiameterDimension(const std::vector< boost::optional<IfcDraughtingCalloutElement> >& _Contents)
         : IfcDimensionCurveDirectedCallout(_Contents) {}

      virtual std::string className() const { return "IfcDiameterDimension"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeSelect<IfcDraughtingCalloutElementWriterVisitor>(Contents);
         w.endEntity();
      }

   };

} // namespace ifc2x3

