#ifndef IFC2X3_IFCDOCUMENTELECTRONICFORMAT_H_INCLUDED
#define IFC2X3_IFCDOCUMENTELECTRONICFORMAT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"

namespace ifc2x3
{
   class IfcDocumentElectronicFormat : public ifc::Entity
   {
   public:
      virtual ~IfcDocumentElectronicFormat(){}

      IfcDocumentElectronicFormat() = default;

      virtual std::string name() const { return "IfcDocumentElectronicFormat"; }

      boost::optional<IfcLabel> FileExtension; // optional parameter
      boost::optional<IfcLabel> MimeContentType; // optional parameter
      boost::optional<IfcLabel> MimeSubtype; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(FileExtension);
         w.writeAttributeValueScalar(MimeContentType);
         w.writeAttributeValueScalar(MimeSubtype);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
