#ifndef IFC2X3_IFCEXTENDEDMATERIALPROPERTIES_H_INCLUDED
#define IFC2X3_IFCEXTENDEDMATERIALPROPERTIES_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcMaterialProperties.h"
#include "IfcProperty.h"

namespace ifc2x3
{
   class IfcExtendedMaterialProperties : public IfcMaterialProperties
   {
   public:
      virtual ~IfcExtendedMaterialProperties(){}

      IfcExtendedMaterialProperties() = default;

      IfcExtendedMaterialProperties(IfcMaterial* _Material, const std::vector<IfcProperty*>& _ExtendedProperties, const IfcLabel& _Name)
         : IfcMaterialProperties(_Material), ExtendedProperties(_ExtendedProperties), Name(_Name) {}

      virtual std::string name() const { return "IfcExtendedMaterialProperties"; }

      std::vector<IfcProperty*> ExtendedProperties; // required parameter
      boost::optional<IfcText> Description; // optional parameter
      boost::optional<IfcLabel> Name; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Material);
         w.writeAttributeInstanceList(ExtendedProperties);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
