#ifndef IFC2X3_IFCELECTRICALBASEPROPERTIES_H_INCLUDED
#define IFC2X3_IFCELECTRICALBASEPROPERTIES_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcEnergyProperties.h"

namespace ifc2x3
{
   class IfcElectricalBaseProperties : public IfcEnergyProperties
   {
   public:
      virtual ~IfcElectricalBaseProperties(){}

      IfcElectricalBaseProperties() = default;

      IfcElectricalBaseProperties(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const IfcElectricVoltageMeasure& _InputVoltage, const IfcFrequencyMeasure& _InputFrequency, const int& _InputPhase)
         : IfcEnergyProperties(_GlobalId, _OwnerHistory), InputVoltage(_InputVoltage), InputFrequency(_InputFrequency), InputPhase(_InputPhase) {}

      virtual std::string name() const { return "IfcElectricalBaseProperties"; }

      boost::optional<IfcElectricCurrentEnum> ElectricCurrentType; // optional parameter
      boost::optional<IfcElectricVoltageMeasure> InputVoltage; // required parameter
      boost::optional<IfcFrequencyMeasure> InputFrequency; // required parameter
      boost::optional<IfcElectricCurrentMeasure> FullLoadCurrent; // optional parameter
      boost::optional<IfcElectricCurrentMeasure> MinimumCircuitCurrent; // optional parameter
      boost::optional<IfcPowerMeasure> MaximumPowerInput; // optional parameter
      boost::optional<IfcPowerMeasure> RatedPowerInput; // optional parameter
      boost::optional<int> InputPhase; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueEnumeration(IfcEnergySequenceEnumStringMap, EnergySequence);
         w.writeAttributeValueScalar(UserDefinedEnergySequence);
         w.writeAttributeValueEnumeration(IfcElectricCurrentEnumStringMap, ElectricCurrentType);
         w.writeAttributeValueScalar(InputVoltage);
         w.writeAttributeValueScalar(InputFrequency);
         w.writeAttributeValueScalar(FullLoadCurrent);
         w.writeAttributeValueScalar(MinimumCircuitCurrent);
         w.writeAttributeValueScalar(MaximumPowerInput);
         w.writeAttributeValueScalar(RatedPowerInput);
         w.writeAttributeValueScalar(InputPhase);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
