#ifndef IFC2X3_IFCELEMENTASSEMBLY_H_INCLUDED
#define IFC2X3_IFCELEMENTASSEMBLY_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcElement.h"

namespace ifc2x3
{
   class IfcElementAssembly : public IfcElement
   {
   public:
      virtual ~IfcElementAssembly(){}

      IfcElementAssembly() = default;

      IfcElementAssembly(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const IfcElementAssemblyTypeEnum& _PredefinedType)
         : IfcElement(_GlobalId, _OwnerHistory), PredefinedType(_PredefinedType) {}

      virtual std::string name() const { return "IfcElementAssembly"; }

      boost::optional<IfcAssemblyPlaceEnum> AssemblyPlace; // optional parameter
      boost::optional<IfcElementAssemblyTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValueScalar(Tag);
         w.writeAttributeValueEnumeration(IfcAssemblyPlaceEnumStringMap, AssemblyPlace);
         w.writeAttributeValueEnumeration(IfcElementAssemblyTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
