// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcMaterialProperties.h"
#include "IfcProperty.h"

namespace ifc2x3
{
   class IfcExtendedMaterialProperties : public IfcMaterialProperties
   {
   public:
      virtual ~IfcExtendedMaterialProperties(){}

      explicit IfcExtendedMaterialProperties() = default;

      explicit IfcExtendedMaterialProperties(IfcMaterial* _Material, const std::vector<IfcProperty*>& _ExtendedProperties, const IfcLabel& _Name)
         : IfcMaterialProperties(_Material), ExtendedProperties(_ExtendedProperties), Name(_Name) {}

      virtual std::string className() const { return "IfcExtendedMaterialProperties"; }

      std::vector<IfcProperty*> ExtendedProperties; // required parameter
      boost::optional<IfcText> Description; // optional parameter
      boost::optional<IfcLabel> Name; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Material);
         w.writeAttributeInstance(ExtendedProperties);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

