#ifndef IFC2X3_IFCFACETEDBREP_H_INCLUDED
#define IFC2X3_IFCFACETEDBREP_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcManifoldSolidBrep.h"

namespace ifc2x3
{
   class IfcFacetedBrep : public IfcManifoldSolidBrep
   {
   public:
      virtual ~IfcFacetedBrep(){}

      IfcFacetedBrep() = default;

      IfcFacetedBrep(IfcClosedShell* _Outer)
         : IfcManifoldSolidBrep(_Outer) {}

      virtual std::string name() const { return "IfcFacetedBrep"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Outer);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
