#ifndef IFC2X3_IFCFEATUREELEMENTADDITION_H_INCLUDED
#define IFC2X3_IFCFEATUREELEMENTADDITION_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcFeatureElement.h"

namespace ifc2x3
{
   class IfcFeatureElementAddition : public IfcFeatureElement
   {
   public:
      virtual ~IfcFeatureElementAddition(){}

      IfcFeatureElementAddition() = default;

      IfcFeatureElementAddition(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcFeatureElement(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcFeatureElementAddition"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValueScalar(Tag);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
