// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcProfileProperties.h"

namespace ifc2x3
{
   class IfcGeneralProfileProperties : public IfcProfileProperties
   {
   public:
      virtual ~IfcGeneralProfileProperties(){}

      explicit IfcGeneralProfileProperties() = default;

      virtual std::string className() const { return "IfcGeneralProfileProperties"; }

      boost::optional<IfcMassPerLengthMeasure> PhysicalWeight; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> Perimeter; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> MinimumPlateThickness; // optional parameter
      boost::optional<IfcPositiveLengthMeasure> MaximumPlateThickness; // optional parameter
      boost::optional<IfcAreaMeasure> CrossSectionArea; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(ProfileName);
         w.writeAttributeInstance(ProfileDefinition);
         w.writeAttributeValue(PhysicalWeight);
         w.writeAttributeValue(Perimeter);
         w.writeAttributeValue(MinimumPlateThickness);
         w.writeAttributeValue(MaximumPlateThickness);
         w.writeAttributeValue(CrossSectionArea);
         w.endEntity();
      }

   };

} // namespace ifc2x3

