#ifndef IFC2X3_IFCLABORRESOURCE_H_INCLUDED
#define IFC2X3_IFCLABORRESOURCE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcConstructionResource.h"

namespace ifc2x3
{
   class IfcLaborResource : public IfcConstructionResource
   {
   public:
      virtual ~IfcLaborResource(){}

      IfcLaborResource() = default;

      IfcLaborResource(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcConstructionResource(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcLaborResource"; }

      boost::optional<IfcText> SkillSet; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeValueScalar(ResourceIdentifier);
         w.writeAttributeValueScalar(ResourceGroup);
         w.writeAttributeValueEnumeration(IfcResourceConsumptionEnumStringMap, ResourceConsumption);
         w.writeAttributeInstance(BaseQuantity);
         w.writeAttributeValueScalar(SkillSet);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
