#ifndef IFC2X3_IFCLINEARDIMENSION_H_INCLUDED
#define IFC2X3_IFCLINEARDIMENSION_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcDimensionCurveDirectedCallout.h"

namespace ifc2x3
{
   class IfcLinearDimension : public IfcDimensionCurveDirectedCallout
   {
   public:
      virtual ~IfcLinearDimension(){}

      IfcLinearDimension() = default;

      IfcLinearDimension(const std::vector<boost::optional<IfcDraughtingCalloutElement>>& _Contents)
         : IfcDimensionCurveDirectedCallout(_Contents) {}

      virtual std::string name() const { return "IfcLinearDimension"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeSelectList<IfcDraughtingCalloutElementWriterVisitor>(Contents);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
