#ifndef IFC2X3_IFCLIGHTSOURCESPOT_H_INCLUDED
#define IFC2X3_IFCLIGHTSOURCESPOT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcLightSourcePositional.h"
#include "IfcDirection.h"

namespace ifc2x3
{
   class IfcLightSourceSpot : public IfcLightSourcePositional
   {
   public:
      virtual ~IfcLightSourceSpot(){}

      IfcLightSourceSpot() = default;

      IfcLightSourceSpot(IfcColourRgb* _LightColour, IfcCartesianPoint* _Position, const IfcPositiveLengthMeasure& _Radius, const IfcReal& _ConstantAttenuation, const IfcReal& _DistanceAttenuation, const IfcReal& _QuadricAttenuation, IfcDirection* _Orientation, const IfcPositivePlaneAngleMeasure& _SpreadAngle, const IfcPositivePlaneAngleMeasure& _BeamWidthAngle)
         : IfcLightSourcePositional(_LightColour, _Position, _Radius, _ConstantAttenuation, _DistanceAttenuation, _QuadricAttenuation), Orientation(_Orientation), SpreadAngle(_SpreadAngle), BeamWidthAngle(_BeamWidthAngle) {}

      virtual std::string name() const { return "IfcLightSourceSpot"; }

      IfcDirection* Orientation; // required parameter
      boost::optional<IfcReal> ConcentrationExponent; // optional parameter
      boost::optional<IfcPositivePlaneAngleMeasure> SpreadAngle; // required parameter
      boost::optional<IfcPositivePlaneAngleMeasure> BeamWidthAngle; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeInstance(LightColour);
         w.writeAttributeValueScalar(AmbientIntensity);
         w.writeAttributeValueScalar(Intensity);
         w.writeAttributeInstance(Position);
         w.writeAttributeValueScalar(Radius);
         w.writeAttributeValueScalar(ConstantAttenuation);
         w.writeAttributeValueScalar(DistanceAttenuation);
         w.writeAttributeValueScalar(QuadricAttenuation);
         w.writeAttributeInstance(Orientation);
         w.writeAttributeValueScalar(ConcentrationExponent);
         w.writeAttributeValueScalar(SpreadAngle);
         w.writeAttributeValueScalar(BeamWidthAngle);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
