#ifndef IFC2X3_IFCMANIFOLDSOLIDBREP_H_INCLUDED
#define IFC2X3_IFCMANIFOLDSOLIDBREP_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcSolidModel.h"
#include "IfcClosedShell.h"

namespace ifc2x3
{
   class IfcManifoldSolidBrep : public IfcSolidModel
   {
   public:
      virtual ~IfcManifoldSolidBrep(){}

      IfcManifoldSolidBrep() = default;

      IfcManifoldSolidBrep(IfcClosedShell* _Outer)
         : IfcSolidModel(), Outer(_Outer) {}

      virtual std::string name() const { return "IfcManifoldSolidBrep"; }

      IfcClosedShell* Outer; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Outer);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
