// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcMaterialLayer.h"

namespace ifc2x3
{
   class IfcMaterialLayerSet : public ifc::Entity
   {
   public:
      virtual ~IfcMaterialLayerSet(){}

      explicit IfcMaterialLayerSet() = default;

      explicit IfcMaterialLayerSet(const std::vector<IfcMaterialLayer*>& _MaterialLayers)
         : ifc::Entity(), MaterialLayers(_MaterialLayers) {}

      virtual std::string className() const { return "IfcMaterialLayerSet"; }

      std::vector<IfcMaterialLayer*> MaterialLayers; // required parameter
      boost::optional<IfcLabel> LayerSetName; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(MaterialLayers);
         w.writeAttributeValue(LayerSetName);
         w.endEntity();
      }

   };

} // namespace ifc2x3

