#ifndef IFC2X3_IFCMATERIALLAYERSETUSAGE_H_INCLUDED
#define IFC2X3_IFCMATERIALLAYERSETUSAGE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcMaterialLayerSet.h"

namespace ifc2x3
{
   class IfcMaterialLayerSetUsage : public ifc::Entity
   {
   public:
      virtual ~IfcMaterialLayerSetUsage(){}

      IfcMaterialLayerSetUsage() = default;

      IfcMaterialLayerSetUsage(IfcMaterialLayerSet* _ForLayerSet, const IfcLayerSetDirectionEnum& _LayerSetDirection, const IfcDirectionSenseEnum& _DirectionSense, const IfcLengthMeasure& _OffsetFromReferenceLine)
         : ifc::Entity(), ForLayerSet(_ForLayerSet), LayerSetDirection(_LayerSetDirection), DirectionSense(_DirectionSense), OffsetFromReferenceLine(_OffsetFromReferenceLine) {}

      virtual std::string name() const { return "IfcMaterialLayerSetUsage"; }

      IfcMaterialLayerSet* ForLayerSet; // required parameter
      boost::optional<IfcLayerSetDirectionEnum> LayerSetDirection; // required parameter
      boost::optional<IfcDirectionSenseEnum> DirectionSense; // required parameter
      boost::optional<IfcLengthMeasure> OffsetFromReferenceLine; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(ForLayerSet);
         w.writeAttributeValueEnumeration(IfcLayerSetDirectionEnumStringMap, LayerSetDirection);
         w.writeAttributeValueEnumeration(IfcDirectionSenseEnumStringMap, DirectionSense);
         w.writeAttributeValueScalar(OffsetFromReferenceLine);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
