#ifndef IFC2X3_IFCMATERIALSELECT_H_INCLUDED
#define IFC2X3_IFCMATERIALSELECT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"

#include "IfcMaterial.h"
#include "IfcMaterialList.h"
#include "IfcMaterialLayerSetUsage.h"
#include "IfcMaterialLayerSet.h"
#include "IfcMaterialLayer.h"

namespace ifc2x3
{
   typedef boost::variant<IfcMaterial*, IfcMaterialList*, IfcMaterialLayerSetUsage*, IfcMaterialLayerSet*, IfcMaterialLayer*> IfcMaterialSelect;

   class IfcMaterialSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcMaterialSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcMaterial* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcMaterialList* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcMaterialLayerSetUsage* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcMaterialLayerSet* p) const
      {
         m_w.writeAttributeInstance(p);
      }
      void operator() (IfcMaterialLayer* p) const
      {
         m_w.writeAttributeInstance(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
#endif
