#ifndef IFC2X3_IFCNAMEDUNIT_H_INCLUDED
#define IFC2X3_IFCNAMEDUNIT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcDimensionalExponents.h"

namespace ifc2x3
{
   class IfcNamedUnit : public ifc::Entity
   {
   public:
      virtual ~IfcNamedUnit(){}

      IfcNamedUnit() = default;

      IfcNamedUnit(IfcDimensionalExponents* _Dimensions, const IfcUnitEnum& _UnitType)
         : ifc::Entity(), Dimensions(_Dimensions), UnitType(_UnitType) {}

      virtual std::string name() const { return "IfcNamedUnit"; }

      IfcDimensionalExponents* Dimensions; // required parameter
      boost::optional<IfcUnitEnum> UnitType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Dimensions,true);
         w.writeAttributeValueEnumeration(IfcUnitEnumStringMap, UnitType);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
