// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcHalfSpaceSolid.h"
#include "IfcAxis2Placement3D.h"
#include "IfcBoundedCurve.h"

namespace ifc2x3
{
   class IfcPolygonalBoundedHalfSpace : public IfcHalfSpaceSolid
   {
   public:
      virtual ~IfcPolygonalBoundedHalfSpace(){}

      explicit IfcPolygonalBoundedHalfSpace() = default;

      explicit IfcPolygonalBoundedHalfSpace(IfcSurface* _BaseSurface, const bool& _AgreementFlag, IfcAxis2Placement3D* _Position, IfcBoundedCurve* _PolygonalBoundary)
         : IfcHalfSpaceSolid(_BaseSurface, _AgreementFlag), Position(_Position), PolygonalBoundary(_PolygonalBoundary) {}

      virtual std::string className() const { return "IfcPolygonalBoundedHalfSpace"; }

      IfcAxis2Placement3D* Position; // required parameter
      IfcBoundedCurve* PolygonalBoundary; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(BaseSurface);
         w.writeAttributeValue(AgreementFlag);
         w.writeAttributeInstance(Position);
         w.writeAttributeInstance(PolygonalBoundary);
         w.endEntity();
      }

   };

} // namespace ifc2x3

