#ifndef IFC2X3_IFCPREDEFINEDDIMENSIONSYMBOL_H_INCLUDED
#define IFC2X3_IFCPREDEFINEDDIMENSIONSYMBOL_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcPreDefinedSymbol.h"

namespace ifc2x3
{
   class IfcPreDefinedDimensionSymbol : public IfcPreDefinedSymbol
   {
   public:
      virtual ~IfcPreDefinedDimensionSymbol(){}

      IfcPreDefinedDimensionSymbol() = default;

      IfcPreDefinedDimensionSymbol(const IfcLabel& _Name)
         : IfcPreDefinedSymbol(_Name) {}

      virtual std::string name() const { return "IfcPreDefinedDimensionSymbol"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
