// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSimpleProperty.h"
#include "IfcObjectReferenceSelect.h"

namespace ifc2x3
{
   class IfcPropertyReferenceValue : public IfcSimpleProperty
   {
   public:
      virtual ~IfcPropertyReferenceValue(){}

      explicit IfcPropertyReferenceValue() = default;

      explicit IfcPropertyReferenceValue(const IfcIdentifier& _Name, const IfcObjectReferenceSelect& _PropertyReference)
         : IfcSimpleProperty(_Name), PropertyReference(_PropertyReference) {}

      virtual std::string className() const { return "IfcPropertyReferenceValue"; }

      boost::optional<IfcLabel> UsageName; // optional parameter
      boost::optional<IfcObjectReferenceSelect> PropertyReference; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(UsageName);
         w.writeAttributeSelect<IfcObjectReferenceSelectWriterVisitor>(PropertyReference);
         w.endEntity();
      }

   };

} // namespace ifc2x3

