// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSimpleProperty.h"
#include "IfcValue.h"
#include "IfcPropertyEnumeration.h"

namespace ifc2x3
{
   class IfcPropertyEnumeratedValue : public IfcSimpleProperty
   {
   public:
      virtual ~IfcPropertyEnumeratedValue(){}

      explicit IfcPropertyEnumeratedValue() = default;

      explicit IfcPropertyEnumeratedValue(const IfcIdentifier& _Name, const std::vector< boost::optional<IfcValue> >& _EnumerationValues)
         : IfcSimpleProperty(_Name), EnumerationValues(_EnumerationValues) {}

      virtual std::string className() const { return "IfcPropertyEnumeratedValue"; }

      std::vector< boost::optional<IfcValue> > EnumerationValues; // required parameter
      IfcPropertyEnumeration* EnumerationReference; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeSelect<IfcValueWriterVisitor>(EnumerationValues);
         w.writeAttributeInstance(EnumerationReference);
         w.endEntity();
      }

   };

} // namespace ifc2x3

