#ifndef IFC2X3_IFCPRODUCT_H_INCLUDED
#define IFC2X3_IFCPRODUCT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcObject.h"
#include "IfcObjectPlacement.h"
#include "IfcProductRepresentation.h"

namespace ifc2x3
{
   class IfcProduct : public IfcObject
   {
   public:
      virtual ~IfcProduct(){}

      IfcProduct() = default;

      IfcProduct(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcObject(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcProduct"; }

      IfcObjectPlacement* ObjectPlacement; // optional parameter
      IfcProductRepresentation* Representation; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
