// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcMaterialProperties.h"

namespace ifc2x3
{
   class IfcProductsOfCombustionProperties : public IfcMaterialProperties
   {
   public:
      virtual ~IfcProductsOfCombustionProperties(){}

      explicit IfcProductsOfCombustionProperties() = default;

      explicit IfcProductsOfCombustionProperties(IfcMaterial* _Material)
         : IfcMaterialProperties(_Material) {}

      virtual std::string className() const { return "IfcProductsOfCombustionProperties"; }

      boost::optional<IfcSpecificHeatCapacityMeasure> SpecificHeatCapacity; // optional parameter
      boost::optional<IfcPositiveRatioMeasure> N20Content; // optional parameter
      boost::optional<IfcPositiveRatioMeasure> COContent; // optional parameter
      boost::optional<IfcPositiveRatioMeasure> CO2Content; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Material);
         w.writeAttributeValue(SpecificHeatCapacity);
         w.writeAttributeValue(N20Content);
         w.writeAttributeValue(COContent);
         w.writeAttributeValue(CO2Content);
         w.endEntity();
      }

   };

} // namespace ifc2x3

