// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcControl.h"
#include "IfcRelAssignsToProjectOrder.h"

namespace ifc2x3
{
   class IfcProjectOrderRecord : public IfcControl
   {
   public:
      virtual ~IfcProjectOrderRecord(){}

      explicit IfcProjectOrderRecord() = default;

      explicit IfcProjectOrderRecord(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const std::vector<IfcRelAssignsToProjectOrder*>& _Records, const IfcProjectOrderRecordTypeEnum& _PredefinedType)
         : IfcControl(_GlobalId, _OwnerHistory), Records(_Records), PredefinedType(_PredefinedType) {}

      virtual std::string className() const { return "IfcProjectOrderRecord"; }

      std::vector<IfcRelAssignsToProjectOrder*> Records; // required parameter
      boost::optional<IfcProjectOrderRecordTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(Records);
         w.writeAttributeValue(IfcProjectOrderRecordTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc2x3

