// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcPhysicalSimpleQuantity.h"

namespace ifc2x3
{
   class IfcQuantityTime : public IfcPhysicalSimpleQuantity
   {
   public:
      virtual ~IfcQuantityTime(){}

      explicit IfcQuantityTime() = default;

      explicit IfcQuantityTime(const IfcLabel& _Name, const IfcTimeMeasure& _TimeValue)
         : IfcPhysicalSimpleQuantity(_Name), TimeValue(_TimeValue) {}

      virtual std::string className() const { return "IfcQuantityTime"; }

      boost::optional<IfcTimeMeasure> TimeValue; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeInstance(Unit);
         w.writeAttributeValue(TimeValue);
         w.endEntity();
      }

   };

} // namespace ifc2x3

