#ifndef IFC2X3_IFCREINFORCINGBAR_H_INCLUDED
#define IFC2X3_IFCREINFORCINGBAR_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcReinforcingElement.h"

namespace ifc2x3
{
   class IfcReinforcingBar : public IfcReinforcingElement
   {
   public:
      virtual ~IfcReinforcingBar(){}

      IfcReinforcingBar() = default;

      IfcReinforcingBar(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const IfcPositiveLengthMeasure& _NominalDiameter, const IfcAreaMeasure& _CrossSectionArea, const IfcReinforcingBarRoleEnum& _BarRole)
         : IfcReinforcingElement(_GlobalId, _OwnerHistory), NominalDiameter(_NominalDiameter), CrossSectionArea(_CrossSectionArea), BarRole(_BarRole) {}

      virtual std::string name() const { return "IfcReinforcingBar"; }

      boost::optional<IfcPositiveLengthMeasure> NominalDiameter; // required parameter
      boost::optional<IfcAreaMeasure> CrossSectionArea; // required parameter
      boost::optional<IfcPositiveLengthMeasure> BarLength; // optional parameter
      boost::optional<IfcReinforcingBarRoleEnum> BarRole; // required parameter
      boost::optional<IfcReinforcingBarSurfaceEnum> BarSurface; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValueScalar(Tag);
         w.writeAttributeValueScalar(SteelGrade);
         w.writeAttributeValueScalar(NominalDiameter);
         w.writeAttributeValueScalar(CrossSectionArea);
         w.writeAttributeValueScalar(BarLength);
         w.writeAttributeValueEnumeration(IfcReinforcingBarRoleEnumStringMap, BarRole);
         w.writeAttributeValueEnumeration(IfcReinforcingBarSurfaceEnumStringMap, BarSurface);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
