#ifndef IFC2X3_IFCRELCONNECTS_H_INCLUDED
#define IFC2X3_IFCRELCONNECTS_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcRelationship.h"

namespace ifc2x3
{
   class IfcRelConnects : public IfcRelationship
   {
   public:
      virtual ~IfcRelConnects(){}

      IfcRelConnects() = default;

      IfcRelConnects(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcRelationship(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcRelConnects"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
