// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcRelConnects.h"
#include "IfcElement.h"
#include "IfcStructuralMember.h"

namespace ifc2x3
{
   class IfcRelConnectsStructuralElement : public IfcRelConnects
   {
   public:
      virtual ~IfcRelConnectsStructuralElement(){}

      explicit IfcRelConnectsStructuralElement() = default;

      explicit IfcRelConnectsStructuralElement(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, IfcElement* _RelatingElement, IfcStructuralMember* _RelatedStructuralMember)
         : IfcRelConnects(_GlobalId, _OwnerHistory), RelatingElement(_RelatingElement), RelatedStructuralMember(_RelatedStructuralMember) {}

      virtual std::string className() const { return "IfcRelConnectsStructuralElement"; }

      IfcElement* RelatingElement; // required parameter
      IfcStructuralMember* RelatedStructuralMember; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeInstance(RelatingElement);
         w.writeAttributeInstance(RelatedStructuralMember);
         w.endEntity();
      }

   };

} // namespace ifc2x3

