// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcDocumentSelect.h"
#include "IfcAppliedValue.h"

namespace ifc2x3
{
   class IfcReferencesValueDocument : public ifc::Entity
   {
   public:
      virtual ~IfcReferencesValueDocument(){}

      explicit IfcReferencesValueDocument() = default;

      explicit IfcReferencesValueDocument(const IfcDocumentSelect& _ReferencedDocument, const std::vector<IfcAppliedValue*>& _ReferencingValues)
         : ifc::Entity(), ReferencedDocument(_ReferencedDocument), ReferencingValues(_ReferencingValues) {}

      virtual std::string className() const { return "IfcReferencesValueDocument"; }

      boost::optional<IfcDocumentSelect> ReferencedDocument; // required parameter
      std::vector<IfcAppliedValue*> ReferencingValues; // required parameter
      boost::optional<IfcLabel> Name; // optional parameter
      boost::optional<IfcText> Description; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeSelect<IfcDocumentSelectWriterVisitor>(ReferencedDocument);
         w.writeAttributeInstance(ReferencingValues);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.endEntity();
      }

   };

} // namespace ifc2x3

