#ifndef IFC2X3_IFCRELASSOCIATESAPPROVAL_H_INCLUDED
#define IFC2X3_IFCRELASSOCIATESAPPROVAL_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcRelAssociates.h"
#include "IfcApproval.h"

namespace ifc2x3
{
   class IfcRelAssociatesApproval : public IfcRelAssociates
   {
   public:
      virtual ~IfcRelAssociatesApproval(){}

      IfcRelAssociatesApproval() = default;

      IfcRelAssociatesApproval(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const std::vector<IfcRoot*>& _RelatedObjects, IfcApproval* _RelatingApproval)
         : IfcRelAssociates(_GlobalId, _OwnerHistory, _RelatedObjects), RelatingApproval(_RelatingApproval) {}

      virtual std::string name() const { return "IfcRelAssociatesApproval"; }

      IfcApproval* RelatingApproval; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeInstanceList(RelatedObjects);
         w.writeAttributeInstance(RelatingApproval);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
