// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcSweptAreaSolid.h"
#include "IfcAxis1Placement.h"

namespace ifc2x3
{
   class IfcRevolvedAreaSolid : public IfcSweptAreaSolid
   {
   public:
      virtual ~IfcRevolvedAreaSolid(){}

      explicit IfcRevolvedAreaSolid() = default;

      explicit IfcRevolvedAreaSolid(IfcProfileDef* _SweptArea, IfcAxis2Placement3D* _Position, IfcAxis1Placement* _Axis, const IfcPlaneAngleMeasure& _Angle)
         : IfcSweptAreaSolid(_SweptArea, _Position), Axis(_Axis), Angle(_Angle) {}

      virtual std::string className() const { return "IfcRevolvedAreaSolid"; }

      IfcAxis1Placement* Axis; // required parameter
      boost::optional<IfcPlaneAngleMeasure> Angle; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(SweptArea);
         w.writeAttributeInstance(Position);
         w.writeAttributeInstance(Axis);
         w.writeAttributeValue(Angle);
         w.endEntity();
      }

   };

} // namespace ifc2x3

