#ifndef IFC2X3_IFCRELSERVICESBUILDINGS_H_INCLUDED
#define IFC2X3_IFCRELSERVICESBUILDINGS_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcRelConnects.h"
#include "IfcSystem.h"
#include "IfcSpatialStructureElement.h"

namespace ifc2x3
{
   class IfcRelServicesBuildings : public IfcRelConnects
   {
   public:
      virtual ~IfcRelServicesBuildings(){}

      IfcRelServicesBuildings() = default;

      IfcRelServicesBuildings(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, IfcSystem* _RelatingSystem, const std::vector<IfcSpatialStructureElement*>& _RelatedBuildings)
         : IfcRelConnects(_GlobalId, _OwnerHistory), RelatingSystem(_RelatingSystem), RelatedBuildings(_RelatedBuildings) {}

      virtual std::string name() const { return "IfcRelServicesBuildings"; }

      IfcSystem* RelatingSystem; // required parameter
      std::vector<IfcSpatialStructureElement*> RelatedBuildings; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeInstance(RelatingSystem);
         w.writeAttributeInstanceList(RelatedBuildings);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
