// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcRelAssigns.h"
#include "IfcProcess.h"
#include "IfcMeasureWithUnit.h"

namespace ifc2x3
{
   class IfcRelAssignsToProcess : public IfcRelAssigns
   {
   public:
      virtual ~IfcRelAssignsToProcess(){}

      explicit IfcRelAssignsToProcess() = default;

      explicit IfcRelAssignsToProcess(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const std::vector<IfcObjectDefinition*>& _RelatedObjects, IfcProcess* _RelatingProcess)
         : IfcRelAssigns(_GlobalId, _OwnerHistory, _RelatedObjects), RelatingProcess(_RelatingProcess) {}

      virtual std::string className() const { return "IfcRelAssignsToProcess"; }

      IfcProcess* RelatingProcess; // required parameter
      IfcMeasureWithUnit* QuantityInProcess; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeInstance(RelatedObjects);
         w.writeAttributeValue(IfcObjectTypeEnumStringMap, RelatedObjectsType);
         w.writeAttributeInstance(RelatingProcess);
         w.writeAttributeInstance(QuantityInProcess);
         w.endEntity();
      }

   };

} // namespace ifc2x3

