#ifndef IFC2X3_IFCRELINTERACTIONREQUIREMENTS_H_INCLUDED
#define IFC2X3_IFCRELINTERACTIONREQUIREMENTS_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcRelConnects.h"
#include "IfcSpatialStructureElement.h"
#include "IfcSpaceProgram.h"
#include "IfcSpaceProgram.h"

namespace ifc2x3
{
   class IfcRelInteractionRequirements : public IfcRelConnects
   {
   public:
      virtual ~IfcRelInteractionRequirements(){}

      IfcRelInteractionRequirements() = default;

      IfcRelInteractionRequirements(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, IfcSpaceProgram* _RelatedSpaceProgram, IfcSpaceProgram* _RelatingSpaceProgram)
         : IfcRelConnects(_GlobalId, _OwnerHistory), RelatedSpaceProgram(_RelatedSpaceProgram), RelatingSpaceProgram(_RelatingSpaceProgram) {}

      virtual std::string name() const { return "IfcRelInteractionRequirements"; }

      boost::optional<IfcCountMeasure> DailyInteraction; // optional parameter
      boost::optional<IfcNormalisedRatioMeasure> ImportanceRating; // optional parameter
      IfcSpatialStructureElement* LocationOfInteraction; // optional parameter
      IfcSpaceProgram* RelatedSpaceProgram; // required parameter
      IfcSpaceProgram* RelatingSpaceProgram; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(DailyInteraction);
         w.writeAttributeValueScalar(ImportanceRating);
         w.writeAttributeInstance(LocationOfInteraction);
         w.writeAttributeInstance(RelatedSpaceProgram);
         w.writeAttributeInstance(RelatingSpaceProgram);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
