#ifndef IFC2X3_IFCSTRUCTURALLOADLINEARFORCE_H_INCLUDED
#define IFC2X3_IFCSTRUCTURALLOADLINEARFORCE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcStructuralLoadStatic.h"

namespace ifc2x3
{
   class IfcStructuralLoadLinearForce : public IfcStructuralLoadStatic
   {
   public:
      virtual ~IfcStructuralLoadLinearForce(){}

      IfcStructuralLoadLinearForce() = default;

      virtual std::string name() const { return "IfcStructuralLoadLinearForce"; }

      boost::optional<IfcLinearForceMeasure> LinearForceX; // optional parameter
      boost::optional<IfcLinearForceMeasure> LinearForceY; // optional parameter
      boost::optional<IfcLinearForceMeasure> LinearForceZ; // optional parameter
      boost::optional<IfcLinearMomentMeasure> LinearMomentX; // optional parameter
      boost::optional<IfcLinearMomentMeasure> LinearMomentY; // optional parameter
      boost::optional<IfcLinearMomentMeasure> LinearMomentZ; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(LinearForceX);
         w.writeAttributeValueScalar(LinearForceY);
         w.writeAttributeValueScalar(LinearForceZ);
         w.writeAttributeValueScalar(LinearMomentX);
         w.writeAttributeValueScalar(LinearMomentY);
         w.writeAttributeValueScalar(LinearMomentZ);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
