// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcProduct.h"
#include "IfcStructuralLoad.h"

namespace ifc2x3
{
   class IfcStructuralActivity : public IfcProduct
   {
   public:
      virtual ~IfcStructuralActivity(){}

      explicit IfcStructuralActivity() = default;

      explicit IfcStructuralActivity(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, IfcStructuralLoad* _AppliedLoad, const IfcGlobalOrLocalEnum& _GlobalOrLocal)
         : IfcProduct(_GlobalId, _OwnerHistory), AppliedLoad(_AppliedLoad), GlobalOrLocal(_GlobalOrLocal) {}

      virtual std::string className() const { return "IfcStructuralActivity"; }

      IfcStructuralLoad* AppliedLoad; // required parameter
      boost::optional<IfcGlobalOrLocalEnum> GlobalOrLocal; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeInstance(AppliedLoad);
         w.writeAttributeValue(IfcGlobalOrLocalEnumStringMap, GlobalOrLocal);
         w.endEntity();
      }

   };

} // namespace ifc2x3

