// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcNamedUnit.h"

namespace ifc2x3
{
   class IfcSIUnit : public IfcNamedUnit
   {
   public:
      virtual ~IfcSIUnit(){}

      explicit IfcSIUnit() = default;

      explicit IfcSIUnit(IfcDimensionalExponents* _Dimensions, const IfcUnitEnum& _UnitType, const IfcSIUnitName& _Name)
         : IfcNamedUnit(_Dimensions, _UnitType), Name(_Name) {}

      virtual std::string className() const { return "IfcSIUnit"; }

      boost::optional<IfcSIPrefix> Prefix; // optional parameter
      boost::optional<IfcSIUnitName> Name; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Dimensions,true);
         w.writeAttributeValue(IfcUnitEnumStringMap, UnitType);
         w.writeAttributeValue(IfcSIPrefixStringMap, Prefix);
         w.writeAttributeValue(IfcSIUnitNameStringMap, Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

