// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcRepresentationItem.h"
#include "IfcRepresentationItem.h"
#include "IfcPresentationStyleAssignment.h"

namespace ifc2x3
{
   class IfcStyledItem : public IfcRepresentationItem
   {
   public:
      virtual ~IfcStyledItem(){}

      explicit IfcStyledItem() = default;

      explicit IfcStyledItem(const std::vector<IfcPresentationStyleAssignment*>& _Styles)
         : IfcRepresentationItem(), Styles(_Styles) {}

      virtual std::string className() const { return "IfcStyledItem"; }

      IfcRepresentationItem* Item; // optional parameter
      std::vector<IfcPresentationStyleAssignment*> Styles; // required parameter
      boost::optional<IfcLabel> Name; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(Item);
         w.writeAttributeInstance(Styles);
         w.writeAttributeValue(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

