#ifndef IFC2X3_IFCSTRUCTURALLOADSINGLEDISPLACEMENT_H_INCLUDED
#define IFC2X3_IFCSTRUCTURALLOADSINGLEDISPLACEMENT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcStructuralLoadStatic.h"

namespace ifc2x3
{
   class IfcStructuralLoadSingleDisplacement : public IfcStructuralLoadStatic
   {
   public:
      virtual ~IfcStructuralLoadSingleDisplacement(){}

      IfcStructuralLoadSingleDisplacement() = default;

      virtual std::string name() const { return "IfcStructuralLoadSingleDisplacement"; }

      boost::optional<IfcLengthMeasure> DisplacementX; // optional parameter
      boost::optional<IfcLengthMeasure> DisplacementY; // optional parameter
      boost::optional<IfcLengthMeasure> DisplacementZ; // optional parameter
      boost::optional<IfcPlaneAngleMeasure> RotationalDisplacementRX; // optional parameter
      boost::optional<IfcPlaneAngleMeasure> RotationalDisplacementRY; // optional parameter
      boost::optional<IfcPlaneAngleMeasure> RotationalDisplacementRZ; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(DisplacementX);
         w.writeAttributeValueScalar(DisplacementY);
         w.writeAttributeValueScalar(DisplacementZ);
         w.writeAttributeValueScalar(RotationalDisplacementRX);
         w.writeAttributeValueScalar(RotationalDisplacementRY);
         w.writeAttributeValueScalar(RotationalDisplacementRZ);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
