#ifndef IFC2X3_IFCSTRUCTURALCURVEMEMBER_H_INCLUDED
#define IFC2X3_IFCSTRUCTURALCURVEMEMBER_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcStructuralMember.h"

namespace ifc2x3
{
   class IfcStructuralCurveMember : public IfcStructuralMember
   {
   public:
      virtual ~IfcStructuralCurveMember(){}

      IfcStructuralCurveMember() = default;

      IfcStructuralCurveMember(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const IfcStructuralCurveTypeEnum& _PredefinedType)
         : IfcStructuralMember(_GlobalId, _OwnerHistory), PredefinedType(_PredefinedType) {}

      virtual std::string name() const { return "IfcStructuralCurveMember"; }

      boost::optional<IfcStructuralCurveTypeEnum> PredefinedType; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeInstance(ObjectPlacement);
         w.writeAttributeInstance(Representation);
         w.writeAttributeValueEnumeration(IfcStructuralCurveTypeEnumStringMap, PredefinedType);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
