#ifndef IFC2X3_IFCSURFACESTYLEREFRACTION_H_INCLUDED
#define IFC2X3_IFCSURFACESTYLEREFRACTION_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"

namespace ifc2x3
{
   class IfcSurfaceStyleRefraction : public ifc::Entity
   {
   public:
      virtual ~IfcSurfaceStyleRefraction(){}

      IfcSurfaceStyleRefraction() = default;

      virtual std::string name() const { return "IfcSurfaceStyleRefraction"; }

      boost::optional<IfcReal> RefractionIndex; // optional parameter
      boost::optional<IfcReal> DispersionFactor; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(RefractionIndex);
         w.writeAttributeValueScalar(DispersionFactor);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
