// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcStructuralConnectionCondition.h"

namespace ifc2x3
{
   class IfcSlippageConnectionCondition : public IfcStructuralConnectionCondition
   {
   public:
      virtual ~IfcSlippageConnectionCondition(){}

      explicit IfcSlippageConnectionCondition() = default;

      virtual std::string className() const { return "IfcSlippageConnectionCondition"; }

      boost::optional<IfcLengthMeasure> SlippageX; // optional parameter
      boost::optional<IfcLengthMeasure> SlippageY; // optional parameter
      boost::optional<IfcLengthMeasure> SlippageZ; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(SlippageX);
         w.writeAttributeValue(SlippageY);
         w.writeAttributeValue(SlippageZ);
         w.endEntity();
      }

   };

} // namespace ifc2x3

