#ifndef IFC2X3_IFCSURFACEOFLINEAREXTRUSION_H_INCLUDED
#define IFC2X3_IFCSURFACEOFLINEAREXTRUSION_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcSweptSurface.h"
#include "IfcDirection.h"

namespace ifc2x3
{
   class IfcSurfaceOfLinearExtrusion : public IfcSweptSurface
   {
   public:
      virtual ~IfcSurfaceOfLinearExtrusion(){}

      IfcSurfaceOfLinearExtrusion() = default;

      IfcSurfaceOfLinearExtrusion(IfcProfileDef* _SweptCurve, IfcAxis2Placement3D* _Position, IfcDirection* _ExtrudedDirection, const IfcLengthMeasure& _Depth)
         : IfcSweptSurface(_SweptCurve, _Position), ExtrudedDirection(_ExtrudedDirection), Depth(_Depth) {}

      virtual std::string name() const { return "IfcSurfaceOfLinearExtrusion"; }

      IfcDirection* ExtrudedDirection; // required parameter
      boost::optional<IfcLengthMeasure> Depth; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(SweptCurve);
         w.writeAttributeInstance(Position);
         w.writeAttributeInstance(ExtrudedDirection);
         w.writeAttributeValueScalar(Depth);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
