#ifndef IFC2X3_IFCSURFACETEXTURE_H_INCLUDED
#define IFC2X3_IFCSURFACETEXTURE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcCartesianTransformationOperator2D.h"

namespace ifc2x3
{
   class IfcSurfaceTexture : public ifc::Entity
   {
   public:
      virtual ~IfcSurfaceTexture(){}

      IfcSurfaceTexture() = default;

      IfcSurfaceTexture(const bool& _RepeatS, const bool& _RepeatT, const IfcSurfaceTextureEnum& _TextureType)
         : ifc::Entity(), RepeatS(_RepeatS), RepeatT(_RepeatT), TextureType(_TextureType) {}

      virtual std::string name() const { return "IfcSurfaceTexture"; }

      boost::optional<bool> RepeatS; // required parameter
      boost::optional<bool> RepeatT; // required parameter
      boost::optional<IfcSurfaceTextureEnum> TextureType; // required parameter
      IfcCartesianTransformationOperator2D* TextureTransform; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(RepeatS);
         w.writeAttributeValueScalar(RepeatT);
         w.writeAttributeValueEnumeration(IfcSurfaceTextureEnumStringMap, TextureType);
         w.writeAttributeInstance(TextureTransform);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
