#ifndef IFC2X3_IFCSPECULARHIGHLIGHTSELECT_H_INCLUDED
#define IFC2X3_IFCSPECULARHIGHLIGHTSELECT_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"


namespace ifc2x3
{
   typedef boost::variant<IfcSpecularExponent, IfcSpecularRoughness> IfcSpecularHighlightSelect;

   class IfcSpecularHighlightSelectWriterVisitor : public boost::static_visitor<>
   {
   public:
      class IfcSpecularHighlightSelectWriterVisitor(ifc::StepWriter& w)
         : m_w(w) {}

      void operator() (IfcSpecularExponent p) const
      {
         m_w.writeAttributeValue(p);
      }
   private:
      ifc::StepWriter& m_w;
   };

}
#endif
