#ifndef IFC2X3_IFCSCHEDULETIMECONTROL_H_INCLUDED
#define IFC2X3_IFCSCHEDULETIMECONTROL_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcControl.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"
#include "IfcDateTimeSelect.h"

namespace ifc2x3
{
   class IfcScheduleTimeControl : public IfcControl
   {
   public:
      virtual ~IfcScheduleTimeControl(){}

      IfcScheduleTimeControl() = default;

      IfcScheduleTimeControl(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcControl(_GlobalId, _OwnerHistory) {}

      virtual std::string name() const { return "IfcScheduleTimeControl"; }

      boost::optional<IfcDateTimeSelect> ActualStart; // optional parameter
      boost::optional<IfcDateTimeSelect> EarlyStart; // optional parameter
      boost::optional<IfcDateTimeSelect> LateStart; // optional parameter
      boost::optional<IfcDateTimeSelect> ScheduleStart; // optional parameter
      boost::optional<IfcDateTimeSelect> ActualFinish; // optional parameter
      boost::optional<IfcDateTimeSelect> EarlyFinish; // optional parameter
      boost::optional<IfcDateTimeSelect> LateFinish; // optional parameter
      boost::optional<IfcDateTimeSelect> ScheduleFinish; // optional parameter
      boost::optional<IfcTimeMeasure> ScheduleDuration; // optional parameter
      boost::optional<IfcTimeMeasure> ActualDuration; // optional parameter
      boost::optional<IfcTimeMeasure> RemainingTime; // optional parameter
      boost::optional<IfcTimeMeasure> FreeFloat; // optional parameter
      boost::optional<IfcTimeMeasure> TotalFloat; // optional parameter
      boost::optional<bool> IsCritical; // optional parameter
      boost::optional<IfcDateTimeSelect> StatusTime; // optional parameter
      boost::optional<IfcTimeMeasure> StartFloat; // optional parameter
      boost::optional<IfcTimeMeasure> FinishFloat; // optional parameter
      boost::optional<IfcPositiveRatioMeasure> Completion; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(Description);
         w.writeAttributeValueScalar(ObjectType);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(ActualStart);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(EarlyStart);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(LateStart);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(ScheduleStart);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(ActualFinish);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(EarlyFinish);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(LateFinish);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(ScheduleFinish);
         w.writeAttributeValueScalar(ScheduleDuration);
         w.writeAttributeValueScalar(ActualDuration);
         w.writeAttributeValueScalar(RemainingTime);
         w.writeAttributeValueScalar(FreeFloat);
         w.writeAttributeValueScalar(TotalFloat);
         w.writeAttributeValueScalar(IsCritical);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(StatusTime);
         w.writeAttributeValueScalar(StartFloat);
         w.writeAttributeValueScalar(FinishFloat);
         w.writeAttributeValueScalar(Completion);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
