#ifndef IFC2X3_IFCSTRUCTURALLOADSINGLEFORCE_H_INCLUDED
#define IFC2X3_IFCSTRUCTURALLOADSINGLEFORCE_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcStructuralLoadStatic.h"

namespace ifc2x3
{
   class IfcStructuralLoadSingleForce : public IfcStructuralLoadStatic
   {
   public:
      virtual ~IfcStructuralLoadSingleForce(){}

      IfcStructuralLoadSingleForce() = default;

      virtual std::string name() const { return "IfcStructuralLoadSingleForce"; }

      boost::optional<IfcForceMeasure> ForceX; // optional parameter
      boost::optional<IfcForceMeasure> ForceY; // optional parameter
      boost::optional<IfcForceMeasure> ForceZ; // optional parameter
      boost::optional<IfcTorqueMeasure> MomentX; // optional parameter
      boost::optional<IfcTorqueMeasure> MomentY; // optional parameter
      boost::optional<IfcTorqueMeasure> MomentZ; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.writeAttributeValueScalar(ForceX);
         w.writeAttributeValueScalar(ForceY);
         w.writeAttributeValueScalar(ForceZ);
         w.writeAttributeValueScalar(MomentX);
         w.writeAttributeValueScalar(MomentY);
         w.writeAttributeValueScalar(MomentZ);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
