#ifndef IFC2X3_IFCSECTIONPROPERTIES_H_INCLUDED
#define IFC2X3_IFCSECTIONPROPERTIES_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcProfileDef.h"
#include "IfcProfileDef.h"

namespace ifc2x3
{
   class IfcSectionProperties : public ifc::Entity
   {
   public:
      virtual ~IfcSectionProperties(){}

      IfcSectionProperties() = default;

      IfcSectionProperties(const IfcSectionTypeEnum& _SectionType, IfcProfileDef* _StartProfile)
         : ifc::Entity(), SectionType(_SectionType), StartProfile(_StartProfile) {}

      virtual std::string name() const { return "IfcSectionProperties"; }

      boost::optional<IfcSectionTypeEnum> SectionType; // required parameter
      IfcProfileDef* StartProfile; // required parameter
      IfcProfileDef* EndProfile; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueEnumeration(IfcSectionTypeEnumStringMap, SectionType);
         w.writeAttributeInstance(StartProfile);
         w.writeAttributeInstance(EndProfile);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
