#ifndef IFC2X3_IFCSTRUCTURALCONNECTIONCONDITION_H_INCLUDED
#define IFC2X3_IFCSTRUCTURALCONNECTIONCONDITION_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"

namespace ifc2x3
{
   class IfcStructuralConnectionCondition : public ifc::Entity
   {
   public:
      virtual ~IfcStructuralConnectionCondition(){}

      IfcStructuralConnectionCondition() = default;

      virtual std::string name() const { return "IfcStructuralConnectionCondition"; }

      boost::optional<IfcLabel> Name; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValueScalar(Name);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
