#ifndef IFC2X3_IFCTABLEROW_H_INCLUDED
#define IFC2X3_IFCTABLEROW_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcValue.h"

namespace ifc2x3
{
   class IfcTableRow : public ifc::Entity
   {
   public:
      virtual ~IfcTableRow(){}

      IfcTableRow() = default;

      IfcTableRow(const std::vector<boost::optional<IfcValue>>& _RowCells, const bool& _IsHeading)
         : ifc::Entity(), RowCells(_RowCells), IsHeading(_IsHeading) {}

      virtual std::string name() const { return "IfcTableRow"; }

      std::vector<boost::optional<IfcValue>> RowCells; // required parameter
      boost::optional<bool> IsHeading; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeSelectList<IfcValueWriterVisitor>(RowCells);
         w.writeAttributeValueScalar(IsHeading);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
