// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcControl.h"
#include "IfcDateTimeSelect.h"
#include "IfcTimeSeries.h"

namespace ifc2x3
{
   class IfcTimeSeriesSchedule : public IfcControl
   {
   public:
      virtual ~IfcTimeSeriesSchedule(){}

      explicit IfcTimeSeriesSchedule() = default;

      explicit IfcTimeSeriesSchedule(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory, const IfcTimeSeriesScheduleTypeEnum& _TimeSeriesScheduleType, IfcTimeSeries* _TimeSeries)
         : IfcControl(_GlobalId, _OwnerHistory), TimeSeriesScheduleType(_TimeSeriesScheduleType), TimeSeries(_TimeSeries) {}

      virtual std::string className() const { return "IfcTimeSeriesSchedule"; }

      std::vector< boost::optional<IfcDateTimeSelect> > ApplicableDates; // optional parameter
      boost::optional<IfcTimeSeriesScheduleTypeEnum> TimeSeriesScheduleType; // required parameter
      IfcTimeSeries* TimeSeries; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ObjectType);
         w.writeAttributeSelect<IfcDateTimeSelectWriterVisitor>(ApplicableDates);
         w.writeAttributeValue(IfcTimeSeriesScheduleTypeEnumStringMap, TimeSeriesScheduleType);
         w.writeAttributeInstance(TimeSeries);
         w.endEntity();
      }

   };

} // namespace ifc2x3

