// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "IfcObjectDefinition.h"
#include "IfcPropertySetDefinition.h"

namespace ifc2x3
{
   class IfcTypeObject : public IfcObjectDefinition
   {
   public:
      virtual ~IfcTypeObject(){}

      explicit IfcTypeObject() = default;

      explicit IfcTypeObject(const IfcGloballyUniqueId& _GlobalId, IfcOwnerHistory* _OwnerHistory)
         : IfcObjectDefinition(_GlobalId, _OwnerHistory) {}

      virtual std::string className() const { return "IfcTypeObject"; }

      boost::optional<IfcLabel> ApplicableOccurrence; // optional parameter
      std::vector<IfcPropertySetDefinition*> HasPropertySets; // optional parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeValue(GlobalId);
         w.writeAttributeInstance(OwnerHistory);
         w.writeAttributeValue(Name);
         w.writeAttributeValue(Description);
         w.writeAttributeValue(ApplicableOccurrence);
         w.writeAttributeInstance(HasPropertySets);
         w.endEntity();
      }

   };

} // namespace ifc2x3

