// Automatically generated by ifclite express parser from ifc2x3 express file - do not modify

#pragma once

#include "IfcTypeDefinitions.h"
#include "Entity.h"
#include "IfcTimeSeries.h"
#include "IfcDocumentSelect.h"

namespace ifc2x3
{
   class IfcTimeSeriesReferenceRelationship : public ifc::Entity
   {
   public:
      virtual ~IfcTimeSeriesReferenceRelationship(){}

      explicit IfcTimeSeriesReferenceRelationship() = default;

      explicit IfcTimeSeriesReferenceRelationship(IfcTimeSeries* _ReferencedTimeSeries, const std::vector< boost::optional<IfcDocumentSelect> >& _TimeSeriesReferences)
         : ifc::Entity(), ReferencedTimeSeries(_ReferencedTimeSeries), TimeSeriesReferences(_TimeSeriesReferences) {}

      virtual std::string className() const { return "IfcTimeSeriesReferenceRelationship"; }

      IfcTimeSeries* ReferencedTimeSeries; // required parameter
      std::vector< boost::optional<IfcDocumentSelect> > TimeSeriesReferences; // required parameter

   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.writeAttributeInstance(ReferencedTimeSeries);
         w.writeAttributeSelect<IfcDocumentSelectWriterVisitor>(TimeSeriesReferences);
         w.endEntity();
      }

   };

} // namespace ifc2x3

