#ifndef IFC2X3_IFCVERTEX_H_INCLUDED
#define IFC2X3_IFCVERTEX_H_INCLUDED

// Automatically generated by sof_sdai_toolkit from ifc2x3 express file - do not modify

#include "IfcTypeDefinitions.h"
#include "IfcTopologicalRepresentationItem.h"

namespace ifc2x3
{
   class IfcVertex : public IfcTopologicalRepresentationItem
   {
   public:
      virtual ~IfcVertex(){}

      IfcVertex() = default;

      virtual std::string name() const { return "IfcVertex"; }


   protected:
      virtual void serialize(ifc::StepWriter& w) const
      {
         w.beginEntity(this);
         w.endEntity();
      }

   };

} // namespace ifc2x3

#endif
